version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nestjs-postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: job-task
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
